#!/usr/bin/env bash
read -p "Do you want to install the dotfiles? " -r
if [[ ! -z ${REPLY} && ! ${REPLY} =~ ^Y|y ]]; then exit; fi

echo "Linking profile files and directories..."
dotfiles="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

function link_from_home {   #link_from_home (dotfile, prefix)
  file=${1}
  prefix=${2}

  homefile=~/${prefix}$(echo $file | sed -Ee 's/[a-z]+\///')
  target=$(readlink -q ${homefile})
  if [[ ! -z ${target} &&  $(dirname ${target}) == ${dotfiles} ]]; then
    echo "skipping ${homefile} since it is already linked to ${dotfiles}"
  else
    #rm -rf "${homefile}" 2>/dev/null
    mv ${homefile} ${homefile}.backup.predotfiles 2>/dev/null
    ln -s "${dotfiles}/${file}" "${homefile}"
  fi

}

for file in bash_profile bashrc bash_aliases vim vim/vimrc gitignore; do
  link_from_home $file "."  # the original dotfiles
done
for file in Templates; do
  link_from_home $file      # no . prefix for these
done

echo "Setting up git..."
${dotfiles}/bin/git-prefs

echo "Setting up Vim..."
vim +PlugInstall! +qall 2>/dev/null

echo "Done."

echo "Run the following to activate:"
echo "  cd && source .bashrc"
